package com.asterfall.rpg;

import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);setContentView(new GameView());}
 class GameView extends View{
  Paint p=new Paint(); Bitmap chars,mons,tiles; int state=0; float px=19,py=13,camX,camY; int dir=0,hp=120,mp=40,gold=80,xp=0; boolean kai=false,bran=false; Random r=new Random();
  float joyX=0,joyY=0; boolean a=false,b=false; int dialogNpc=-1,battle=0; String dialogText="";
  ArrayList<Npc> ns=new ArrayList<>(); int[] map=new int[40*30];
  class Npc{float x,y;int s;String n,t;Npc(float x,float y,int s,String n,String t){this.x=x;this.y=y;this.s=s;this.n=n;this.t=t;}}
  GameView(){super(MainActivity.this);p.setTypeface(Typeface.create(Typeface.MONOSPACE,Typeface.BOLD));load();buildMap();buildNpcs();}
  void load(){try{chars=BitmapFactory.decodeStream(getAssets().open("characters.png"));mons=BitmapFactory.decodeStream(getAssets().open("monsters.png"));tiles=BitmapFactory.decodeStream(getAssets().open("tileset.png"));}catch(Exception e){}}
  void buildMap(){Arrays.fill(map,0);for(int y=0;y<30;y++)for(int x=0;x<40;x++)if(x<1||y<1||x>38||y>28)map[y*40+x]=8;for(int y=3;y<27;y++)for(int x=3;x<37;x++)if((x<7&&y>4)||(x>32&&y<12))map[y*40+x]=3;for(int x=1;x<39;x++)for(int y=14;y<17;y++)map[y*40+x]=1;for(int y=3;y<15;y++)map[y*40+19]=1;for(int y=2;y<7;y++)for(int x=27;x<33;x++)map[y*40+x]=2;int[][] q={{4,4},{5,4},{6,4},{4,5},{7,6},{9,4},{10,4},{33,19},{34,19},{35,19},{34,20},{35,20},{5,23},{6,23},{7,23},{31,25},{32,25},{33,25}};for(int[]a:q)map[a[1]*40+a[0]]=8;for(int y=8;y<12;y++)for(int x=8;x<13;x++)map[y*40+x]=10;for(int y=19;y<23;y++)for(int x=24;x<29;x++)map[y*40+x]=11;}
  void buildNpcs(){ns.add(new Npc(19,12,1,"Mira the Archivist","The star beneath Asterfall is waking. Find the four Dawn Sigils before the Hollow King does."));ns.add(new Npc(15,15,2,"Kai the Mage","I can read the old runes. Let me travel with you and turn forbidden magic against our enemies."));ns.add(new Npc(23,16,3,"Bran the Warrior","Something stalks the farms at night. I will guard Asterfall while you search the eastern ruins."));ns.add(new Npc(11,14,4,"Elder Rowan","Asterfall was built around a fallen star. Legends say its light can save a kingdom—or erase one."));ns.add(new Npc(28,16,5,"Merchant","Potions and supplies for brave travelers! The eastern road is dangerous."));}
  @Override protected void onDraw(Canvas c){super.onDraw(c);if(state==0)title(c);else if(state==1)world(c);else if(state==2){world(c);dialog(c);}else if(state==3)battle(c);else{world(c);menu(c);} }
  void title(Canvas c){c.drawColor(Color.rgb(11,24,48));p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.rgb(255,214,110));p.setTextSize(42);c.drawText("CHRONICLES OF ASTERFALL",getWidth()/2,105,p);p.setColor(Color.WHITE);p.setTextSize(18);c.drawText("Pixel-art adventure RPG",getWidth()/2,145,p);c.drawText("EXPLORE  •  TALK  •  FIGHT  •  GROW",getWidth()/2,178,p);btn(c,getWidth()/2-110,225,220,60,"BEGIN JOURNEY");p.setTextSize(12);p.setColor(Color.LTGRAY);c.drawText("Analog stick: move    A: confirm    B: menu",getWidth()/2,320,p);p.setTextAlign(Paint.Align.LEFT);}
  void world(Canvas c){int tw=48;camX=px*tw-getWidth()/2;camY=py*tw-(getHeight()-70)/2;camX=Math.max(0,Math.min(camX,40*tw-getWidth()));camY=Math.max(0,Math.min(camY,30*tw-(getHeight()-70)));p.setFilterBitmap(false);for(int y=0;y<30;y++)for(int x=0;x<40;x++)tile(c,x*tw-camX,y*tw-camY,map[y*40+x],tw);house(c,8,8,"ARCHIVE");house(c,24,19,"ASTERFALL INN");for(Npc n:ns)charSprite(c,n.x*tw-camX+tw/2,n.y*tw-camY+tw/2,n.s,1.65f);charSprite(c,getWidth()/2,(getHeight()-70)/2,0,2.0f);p.setColor(Color.argb(225,7,15,29));c.drawRect(0,0,getWidth(),58,p);p.setColor(Color.WHITE);p.setTextSize(14);c.drawText("Asterfall Village",16,22,p);c.drawText("HP "+hp+"/120   MP "+mp+"/40   Lv 4   Gold "+gold,16,44,p);controls(c);}
  void tile(Canvas c,int x,int y,int id,int s){int sx=(id%8)*16,sy=(id/8)*16;c.drawBitmap(tiles,new Rect(sx,sy,sx+16,sy+16),new Rect(x,y,x+s,y+s),p);}
  void house(Canvas c,int tx,int ty,String lab){float x=tx*48-camX,y=ty*48-camY;p.setColor(Color.rgb(128,52,43));Path z=new Path();z.moveTo(x,y+20);z.lineTo(x+120,y+20);z.lineTo(x+100,y);z.lineTo(x+20,y);z.close();c.drawPath(z,p);p.setColor(Color.rgb(222,188,128));c.drawRect(x+15,y+20,x+105,y+125,p);p.setColor(Color.rgb(76,48,37));c.drawRect(x+53,y+78,x+67,y+125,p);p.setColor(Color.WHITE);p.setTextSize(9);c.drawText(lab,x+15,y+140,p);}
  void charSprite(Canvas c,float cx,float cy,int i,float sc){int col=i%8,row=i/8;Rect src=new Rect(col*32,row*32,col*32+32,row*32+32);float sz=32*sc;c.drawBitmap(chars,src,new RectF(cx-sz/2,cy-sz/2,cx+sz/2,cy+sz/2),p);}
  void controls(Canvas c){float x=95,y=getHeight()-88;p.setColor(Color.argb(100,0,0,0));c.drawCircle(x,y,70,p);p.setColor(Color.argb(180,220,225,235));c.drawCircle(x+joyX*35,y+joyY*35,31,p);circle(c,getWidth()-100,getHeight()-110,46,"A");circle(c,getWidth()-205,getHeight()-70,40,"B");}
  void circle(Canvas c,float x,float y,float rr,String s){p.setColor(Color.argb(200,15,25,42));c.drawCircle(x,y,rr,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.rgb(235,195,80));c.drawCircle(x,y,rr,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(rr*.62f);c.drawText(s,x,y+rr*.22f,p);p.setTextAlign(Paint.Align.LEFT);}
  void dialog(Canvas c){p.setColor(Color.argb(245,6,14,28));c.drawRoundRect(24,getHeight()-190,getWidth()-24,getHeight()-25,14,14,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.rgb(235,195,80));c.drawRoundRect(24,getHeight()-190,getWidth()-24,getHeight()-25,14,14,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(255,214,110));p.setTextSize(17);c.drawText(ns.get(dialogNpc).n,48,getHeight()-152,p);p.setColor(Color.WHITE);p.setTextSize(15);wrap(c,ns.get(dialogNpc).t,48,getHeight()-115,getWidth()-90);p.setTextSize(11);p.setColor(Color.LTGRAY);c.drawText("A  continue",getWidth()-115,getHeight()-45,p);}
  void wrap(Canvas c,String s,float x,float y,float w){String[] a=s.split(" ");String line="";float yy=y;for(String q:a){if(p.measureText(line+q)>w){c.drawText(line,x,yy,p);yy+=21;line="";}line+=q+" ";}c.drawText(line,x,yy,p);}
  void menu(Canvas c){p.setColor(Color.argb(247,7,16,34));c.drawRoundRect(70,65,getWidth()-70,getHeight()-65,18,18,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.rgb(235,195,80));c.drawRoundRect(70,65,getWidth()-70,getHeight()-65,18,18,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.WHITE);p.setTextSize(25);c.drawText("JOURNAL & MENU",105,112,p);p.setTextSize(16);c.drawText("Main Quest: Recover the four Dawn Sigils",105,155,p);c.drawText("Party: Hero"+(kai?"  Kai":"")+(bran?"  Bran":""),105,190,p);c.drawText("HP "+hp+"     MP "+mp+"     Gold "+gold+"     XP "+xp,105,225,p);c.drawText("B or A: return to the adventure",105,275,p);}
  void battle(Canvas c){c.drawColor(Color.rgb(18,27,48));p.setColor(Color.rgb(52,85,112));c.drawRect(0,0,getWidth(),getHeight()*.58f,p);p.setColor(Color.rgb(43,91,57));c.drawOval(-100,getHeight()*.35f,getWidth()+100,getHeight()*.83f,p);int col=battle%8;c.drawBitmap(mons,new Rect(col*32,0,col*32+32,32),new RectF(getWidth()*.60f,getHeight()*.17f,getWidth()*.60f+190,getHeight()*.17f+190),p);charSprite(c,getWidth()*.22f,getHeight()*.38f,0,2.7f);p.setColor(Color.argb(245,6,14,28));c.drawRect(0,getHeight()*.63f,getWidth(),getHeight(),p);p.setColor(Color.WHITE);p.setTextSize(18);c.drawText(monName()+" attacks from the wild!",25,getHeight()*.70f,p);btn(c,25,getHeight()*.76f,175,52,"ATTACK");btn(c,220,getHeight()*.76f,175,52,"SKILL");btn(c,415,getHeight()*.76f,175,52,"ITEM");btn(c,610,getHeight()*.76f,145,52,"FLEE");}
  String monName(){return new String[]{"Blue Slime","Moon Wolf","Stone Golem","Crimson Drake"}[battle%4];}
  void btn(Canvas c,float x,float y,float w,float h,String s){p.setColor(Color.rgb(18,31,53));c.drawRoundRect(x,y,x+w,y+h,10,10,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.rgb(235,195,80));c.drawRoundRect(x,y,x+w,y+h,10,10,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(17);c.drawText(s,x+w/2,y+h/2+6,p);p.setTextAlign(Paint.Align.LEFT);}
  void move(float dx,float dy){if(state!=1)return;float sp=.10f;float nx=px+dx*sp,ny=py+dy*sp;if(nx>1&&nx<38&&ny>1&&ny<28&&!blocked(nx,ny)){px=nx;py=ny;dir=Math.abs(dx)>Math.abs(dy)?(dx<0?1:2):(dy<0?3:0);if(map[(int)py*40+(int)px]==0&&r.nextInt(850)==0){battle=r.nextInt(4);state=3;}}}
  boolean blocked(float x,float y){int id=map[(int)y*40+(int)x];return id==8||id==2||id==10||id==11;}
  void interact(){int best=-1;float bd=2.0f;for(int i=0;i<ns.size();i++){float d=(float)Math.hypot(ns.get(i).x-px,ns.get(i).y-py);if(d<bd){bd=d;best=i;}}if(best>=0){dialogNpc=best;state=2;if(best==1)kai=true;if(best==2)bran=true;}}
  void battleAction(int a){if(a==3){state=1;return;}if(a==2){if(gold>=10){gold-=10;hp=Math.min(120,hp+35);}return;}int dmg=15+r.nextInt(20)+(a==1?12:0);if(r.nextInt(100)<20)dmg*=2;xp+=20;gold+=15;state=1;}
  @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();int ac=e.getActionMasked();if(state==0&&ac==1){if(x>getWidth()/2-150&&x<getWidth()/2+150&&y>210&&y<310)state=1;return true;}if(state==3&&ac==1){if(y>getHeight()*.74f){if(x<200)battleAction(0);else if(x<400)battleAction(1);else if(x<600)battleAction(2);else battleAction(3);}return true;}if(state==2&&ac==1){state=1;return true;}if(state==4&&ac==1){state=1;return true;}if(state==1){float bx=95,by=getHeight()-88;if(ac==0||ac==2){float dx=x-bx,dy=y-by,len=(float)Math.hypot(dx,dy);if(len<100){joyX=Math.max(-1,Math.min(1,dx/65));joyY=Math.max(-1,Math.min(1,dy/65));if(len>10)move(joyX,joyY);}if(Math.hypot(x-(getWidth()-100),y-(getHeight()-110))<58)a=true;if(Math.hypot(x-(getWidth()-205),y-(getHeight()-70))<52)b=true;}if(ac==1){if(a){a=false;interact();}if(b){b=false;state=4;}joyX=joyY=0;}return true;}return true;}
 }
}
