package com.aarontap.rpg;

import android.app.Activity;
import android.content.*;
import android.graphics.*;
import android.os.*;
import android.view.*;
import android.widget.Toast;
import java.util.*;

public class MainActivity extends Activity {
 @Override public void onCreate(Bundle b){super.onCreate(b);setTitle("Monster Tamer: A New Journey");setContentView(new Game(this));}

 static class Game extends View {
  Paint p=new Paint(3),t=new Paint(3); Random rng=new Random(); SharedPreferences s; Vibrator vib;
  int screen=0,zone=0,chapter=1,enemy=-1,enemyHp=0,playerHp=120,maxHp=120,level=1,xp=0,gold=100,wins=0,tames=0,selected=0,storyPage=0,dungeon=0,dungeonFloor=0;
  boolean boss=false,defend=false,storySeen=false; ArrayList<Integer> party=new ArrayList<>(); boolean[] caught=new boolean[120]; int[] mlvl=new int[120], weapon=new int[4], armor=new int[4];
  String[] monsters={"Azure Slime","Moss Slime","Ember Slime","Frost Slime","Spark Slime","Moon Slime","Iron Slime","Royal Slime","Bubble Beast","Mud Blob","Greenhorn Goblin","Redcap Goblin","Stone Goblin","Cave Orc","Hill Orc","Brutish Orc","Forest Troll","Stone Troll","Bog Troll","Cyclops","Wolf Pup","Dire Wolf","Moon Wolf","Frost Wolf","Thunder Hound","Wildcat","Sabertooth","Golden Lion","Horned Boar","Iron Boar","Tiny Drake","Red Drake","Blue Drake","Green Drake","Winged Dragon","Stone Dragon","Sea Dragon","Thunder Dragon","Ancient Dragon","Star Dragon","Baby Bat","Night Bat","Vampire Bat","Winged Imp","Red Imp","Blue Imp","Dark Imp","Demon Knight","Ash Demon","Void Demon","Forest Sprite","Leaf Fairy","Bloom Fairy","Mushroomkin","Mandrake","Treant","Ancient Treant","Dryad","Thorn Beast","Bramble King","Sand Scorpion","Rock Crab","Shellback","Cactus Crawler","Dune Beast","Desert Jackal","Sand Worm","Mirage Moth","Sun Beetle","Golden Scarab","River Fish","Piranha","Jellyfish","Sea Serpent","Coral Crab","Tide Turtle","Sharkling","Great Shark","Kraken Spawn","Deep Kraken","Snow Hare","Ice Wolf","Frost Ape","Yeti","Snow Golem","Ice Elemental","Aurora Bird","Glacier Bear","White Stag","Frost Queen","Tiny Golem","Clay Golem","Iron Golem","Obsidian Golem","Clockwork","Copper Knight","Silver Knight","Gold Knight","Crystal Giant","Titan","Ghost","Wisp","Haunted Doll","Bone Dog","Skeleton","Skeleton Mage","Wraith","Grave Knight","Phantom Dragon","Death Herald","Rainbow Bird","Phoenix Chick","Phoenix","Unicorn","Pegasus","Griffin","Chimera","Basilisk","Manticore","World Serpent"};
  String[] zones={"Greenvale","Whisperwood","Sunscar","Moonlit Coast","Frostpeak","Elder Ruins","Skyreach","Shadow Vale"};
  String[] towns={"Greenvale Village","Willowbrook","Dustmere","Coralport","Frostholm","Ruinhaven","Skyspire","Nightfall"};
  String[] chapters={"The First Bond","Whispers in the Woods","The Sunken Crown","Storm over Moonlit Coast","Heart of Frostpeak","The Elder Gate","Road to Skyreach","The World Serpent"};
  String[] npc={"Mira the Innkeeper","Tobin the Smith","Elder Rowan","Lyra the Ranger","Bram the Breeder","Sage Orin","Captain Vale","The Wandering Merchant"};
  String[] weapons={"Wooden Blade","Iron Sword","Knight Saber","Moonsteel","Dragonfang"};
  String[] armors={"Traveler Tunic","Leather Mail","Iron Plate","Frostguard","Elder Robe"};
  String[] skills={"Bite","Spark","Ember Shot","Ice Shard","Heal","Guard Break","Whirlwind","Meteor Roar"};

  Game(Context c){super(c);s=c.getSharedPreferences("monster_tamer_big",0);vib=(Vibrator)c.getSystemService(Context.VIBRATOR_SERVICE);load();t.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));setFocusable(true);}
  void load(){level=s.getInt("level",1);xp=s.getInt("xp",0);gold=s.getInt("gold",100);wins=s.getInt("wins",0);tames=s.getInt("tames",0);chapter=s.getInt("chapter",1);zone=s.getInt("zone",0);playerHp=s.getInt("hp",120);maxHp=80+level*40;dungeon=s.getInt("dungeon",0);for(int i=0;i<120;i++){caught[i]=s.getBoolean("c"+i,false);mlvl[i]=s.getInt("m"+i,1);if(caught[i]&&!party.contains(i)&&party.size()<4)party.add(i);}for(int i=0;i<4;i++){weapon[i]=s.getInt("w"+i,0);armor[i]=s.getInt("a"+i,0);}if(party.isEmpty()){caught[0]=true;party.add(0);tames=1;}}
  void save(){SharedPreferences.Editor e=s.edit().putInt("level",level).putInt("xp",xp).putInt("gold",gold).putInt("wins",wins).putInt("tames",tames).putInt("chapter",chapter).putInt("zone",zone).putInt("hp",playerHp).putInt("dungeon",dungeon);for(int i=0;i<120;i++)if(caught[i])e.putBoolean("c"+i,true).putInt("m"+i,mlvl[i]);for(int i=0;i<4;i++)e.putInt("w"+i,weapon[i]).putInt("a"+i,armor[i]);e.apply();}
  float D(){return getResources().getDisplayMetrics().density;} void bg(Canvas c,int col){c.drawColor(col);} void box(Canvas c,float a,float b,float x,float y,int col){p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawRoundRect(a,b,x,y,18,18,p);} void txt(Canvas c,String q,float x,float y,float z,int col){t.setTextSize(z*D());t.setColor(col);t.setTextAlign(Paint.Align.CENTER);c.drawText(q,x,y,t);} void left(Canvas c,String q,float x,float y,float z,int col){t.setTextSize(z*D());t.setColor(col);t.setTextAlign(Paint.Align.LEFT);c.drawText(q,x,y,t);}
  @Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();bg(c,0xFF0D1724);if(screen==0)title(c,w,h);else if(screen==1)world(c,w,h);else if(screen==2)battle(c,w,h);else if(screen==3)book(c,w,h);else if(screen==4)town(c,w,h);else if(screen==5)equipment(c,w,h);else if(screen==6)breeding(c,w,h);else if(screen==7)dungeon(c,w,h);else story(c,w,h);}
  void title(Canvas c,float w,float h){for(int y=0;y<12;y++)for(int x=0;x<8;x++){p.setColor((x+y)%2==0?0xFF315D42:0xFF3C704D);c.drawRect(x*w/8,y*h/12,(x+1)*w/8,(y+1)*h/12,p);}txt(c,"MONSTER TAMER",w/2,90*D(),32,Color.WHITE);txt(c,"A NEW JOURNEY",w/2,123*D(),18,0xFFFFD45A);drawMonster(c,w/2,h*.36f,34,1.5f);box(c,w*.12f,h*.58f,w*.88f,h*.66f,0xFF17314A);txt(c,"CONTINUE ADVENTURE",w/2,h*.63f,18,Color.WHITE);box(c,w*.12f,h*.69f,w*.88f,h*.77f,0xFF533B29);txt(c,"NEW STORY",w/2,h*.74f,18,Color.WHITE);txt(c,"120 tameable monsters • 8 chapters • dungeons",w/2,h*.86f,12,Color.WHITE);}
  void header(Canvas c,float w,String q){p.setColor(0xFF172A43);c.drawRect(0,0,w,68*D(),p);txt(c,q,w/2,43*D(),21,Color.WHITE);}
  void nav(Canvas c,float w,float h){p.setColor(0xFF172A43);c.drawRect(0,h-68*D(),w,h,p);String[] a={"MAP","BOOK","TOWN","CAMP"};for(int i=0;i<4;i++)txt(c,a[i],w*(.125f+i*.25f),h-28*D(),12,(screen==i+1?0xFFFFD45A:Color.WHITE));}
  void world(Canvas c,float w,float h){header(c,w,"WORLD MAP • "+zones[zone]);float top=78*D();for(int y=0;y<6;y++)for(int x=0;x<5;x++){p.setColor((x+y)%3==0?0xFF356B43:0xFF447A4D);c.drawRect(x*w/5,top+y*67*D(),(x+1)*w/5,top+(y+1)*67*D(),p);}for(int i=0;i<8;i++){float xx=w*(.11f+(i%4)*.26f),yy=top+55*D()+(i/4)*145*D();p.setColor(i<=chapter-1?0xFFFFD45A:0xFF6D7882);c.drawCircle(xx,yy,15*D(),p);txt(c,""+(i+1),xx,yy+5*D(),12,Color.DKGRAY);}box(c,w*.07f,h*.53f,w*.93f,h*.70f,0xE9142233);txt(c,chapters[Math.min(chapter-1,7)],w/2,h*.575f,20,0xFFFFD45A);txt(c,towns[zone],w/2,h*.615f,16,Color.WHITE);txt(c,"Story progress: Chapter "+chapter+" / 8",w/2,h*.655f,13,0xFFD6E4F5);button(c,w*.10f,h*.72f,w*.43f,h*.80f,"EXPLORE",0xFF244F69);button(c,w*.57f,h*.72f,w*.90f,h*.80f,"STORY",0xFF5A3E2C);nav(c,w,h);}
  void battle(Canvas c,float w,float h){header(c,w,boss?"BOSS BATTLE":"WILD ENCOUNTER");drawMonster(c,w*.72f,165*D(),enemy,1.15f);txt(c,monsters[enemy],w*.72f,225*D(),17,Color.WHITE);bar(c,w*.50f,240*D(),w*.94f,258*D(),enemyHp,enemyMax());drawMonster(c,w*.25f,320*D(),party.get(0),1.0f);txt(c,monsters[party.get(0)],w*.25f,375*D(),15,Color.WHITE);txt(c,"Lv "+level+"  HP "+playerHp+"/"+maxHp,w*.25f,400*D(),13,0xFFFFD45A);String[] a={"ATTACK","SKILL","TAME","GUARD","ITEM","RUN"};for(int i=0;i<6;i++){float xx=i%2==0?w*.08f:w*.54f,yy=425*D()+(i/2)*52*D();button(c,xx,yy,xx+w*.38f,yy+42*D(),a[i],i==2?0xFF70492E:0xFF244A68);}txt(c,boss?"Bosses cannot be tamed":"Defeat foes to earn XP, gold and a chance to tame them",w/2,h-82*D(),11,0xFFD6E4F5);}
  int enemyMax(){return boss?180+chapter*90:45+enemy%35+level*7;}
  void book(Canvas c,float w,float h){header(c,w,"MONSTER COMPENDIUM • "+tames+" / 120");int st=(selected/15)*15;for(int i=0;i<15;i++){int id=st+i;if(id>=120)break;float xx=w*(.17f+(i%3)*.33f),yy=95*D()+(i/3)*76*D();drawMonster(c,xx,yy,id,caught[id]?.55f:.42f);txt(c,caught[id]?monsters[id]:"???",xx,yy+28*D(),10,caught[id]?Color.WHITE:0xFF718196);}txt(c,"Page "+(st/15+1)+" / 8",w/2,h-85*D(),12,0xFFFFD45A);nav(c,w,h);}
  void town(Canvas c,float w,float h){header(c,w,towns[zone]);txt(c,"PEOPLE & SERVICES",w/2,98*D(),17,0xFFFFD45A);for(int i=0;i<5;i++){float yy=120*D()+i*62*D();box(c,w*.08f,yy,w*.92f,yy+50*D(),0xFF1D3044);left(c,npc[(zone+i)%npc.length],w*.14f,yy+21*D(),14,Color.WHITE);txt(c,new String[]{"INN","SMITH","QUEST","BREED","SHOP"}[i],w*.78f,yy+31*D(),12,0xFFFFD45A);}box(c,w*.08f,h*.58f,w*.92f,h*.72f,0xFF244B38);txt(c,"Chapter "+chapter+": "+chapters[chapter-1],w/2,h*.625f,15,Color.WHITE);txt(c,"New quests unlock as you travel.",w/2,h*.67f,12,0xFFD6E4F5);nav(c,w,h);}
  void equipment(Canvas c,float w,float h){header(c,w,"ARMORY & EQUIPMENT");txt(c,"HERO",w*.25f,98*D(),16,0xFFFFD45A);txt(c,"Weapon: "+weapons[weapon[0]],w*.25f,130*D(),13,Color.WHITE);txt(c,"Armor: "+armors[armor[0]],w*.25f,157*D(),13,Color.WHITE);txt(c,"Party bonuses",w*.25f,188*D(),14,0xFFFFD45A);txt(c,"ATK +"+(weapon[0]*8)+"  DEF +"+(armor[0]*10),w*.25f,215*D(),13,Color.WHITE);for(int i=0;i<4;i++){float yy=245*D()+i*58*D();box(c,w*.08f,yy,w*.92f,yy+47*D(),0xFF20384C);txt(c,weapons[i+1],w*.33f,yy+19*D(),13,Color.WHITE);txt(c,(50+i*100)+" G",w*.78f,yy+28*D(),12,0xFFFFD45A);}box(c,w*.08f,h*.75f,w*.92f,h*.83f,0xFF5A3D2B);txt(c,"UPGRADE NEXT GEAR",w/2,h*.80f,15,Color.WHITE);}
  void breeding(Canvas c,float w,float h){header(c,w,"BREEDING GROVE");txt(c,"Combine two tamed monsters to hatch a new companion.",w/2,98*D(),12,0xFFD6E4F5);if(party.size()>=2){drawMonster(c,w*.30f,160*D(),party.get(0),.8f);drawMonster(c,w*.70f,160*D(),party.get(1),.8f);txt(c,"+",w/2,165*D(),28,0xFFFFD45A);txt(c,monsters[party.get(0)],w*.30f,205*D(),11,Color.WHITE);txt(c,monsters[party.get(1)],w*.70f,205*D(),11,Color.WHITE);box(c,w*.12f,240*D(),w*.88f,310*D(),0xFF244B38);txt(c,"HATCH EGG • 75 G",w/2,283*D(),17,Color.WHITE);}else txt(c,"Tame two monsters first.",w/2,170*D(),16,Color.WHITE);txt(c,"Breeding can inherit skills and produce rare variants.",w/2,350*D(),12,0xFFD6E4F5);button(c,w*.15f,390*D(),w*.85f,450*D(),"HATCH EGG",0xFF5A3D2B);}
  void dungeon(Canvas c,float w,float h){header(c,w,"DUNGEON • FLOOR "+(dungeonFloor+1));txt(c,"Ancient passages hide rare monsters, treasure and bosses.",w/2,96*D(),12,0xFFD6E4F5);for(int i=0;i<9;i++){float xx=w*.12f+(i%3)*w*.38f,yy=125*D()+(i/3)*82*D();box(c,xx,yy,xx+w*.27f,yy+60*D(),i==dungeonFloor%9?0xFF6A4A2F:0xFF24384A);txt(c,i==8?"BOSS":"ROOM "+(i+1),xx+w*.135f,yy+36*D(),12,Color.WHITE);}txt(c,"Clear rooms to reach the floor guardian.",w/2,405*D(),13,0xFFFFD45A);button(c,w*.12f,440*D(),w*.88f,500*D(),"ENTER ROOM",0xFF244F69);}
  void story(Canvas c,float w,float h){header(c,w,"CHAPTER "+chapter+" • "+chapters[chapter-1]);String[] lines={"A strange light falls beyond the hills.","Old legends say monsters once fought beside people.","The village elder asks you to seek the lost Bondstone.","Your first companion feels the same call.","Across the realm, ancient gates are awakening.","Each chapter reveals a new region and stronger creatures."};box(c,w*.09f,95*D(),w*.91f,330*D(),0xFF1C3042);for(int i=0;i<lines.length;i++)txt(c,lines[i],w/2,(135+i*30)*D(),13,Color.WHITE);button(c,w*.12f,365*D(),w*.88f,425*D(),"CONTINUE STORY",0xFF5A3D2B);}
  void button(Canvas c,float a,float b,float x,float y,String q,int col){box(c,a,b,x,y,col);txt(c,q,(a+x)/2,b+(y-b)*.65f/D(),15,Color.WHITE);}
  void bar(Canvas c,float a,float b,float x,float y,int v,int m){p.setColor(0xFF17202B);c.drawRoundRect(a,b,x,y,8,8,p);p.setColor(0xFF58B56B);float z=Math.max(0,Math.min(1,v/(float)m));c.drawRoundRect(a,b,a+(x-a)*z,y,8,8,p);}
  void drawMonster(Canvas c,float x,float y,int id,float scale){float q=29*D()*scale;int col=Color.rgb(60+(id*31)%150,70+(id*53)%140,90+(id*71)%140);p.setColor(col);c.drawOval(new RectF(x-q,y-q*.7f,x+q,y+q*.75f),p);p.setColor(Color.WHITE);c.drawCircle(x-q*.35f,y-q*.12f,5*D()*scale,p);c.drawCircle(x+q*.35f,y-q*.12f,5*D()*scale,p);p.setColor(Color.DKGRAY);c.drawCircle(x-q*.35f,y-q*.12f,2*D()*scale,p);c.drawCircle(x+q*.35f,y-q*.12f,2*D()*scale,p);if(id%4==0){p.setColor(0xFFFFD45A);Path a=new Path();a.moveTo(x,y-q*1.3f);a.lineTo(x-q*.4f,y-q*.55f);a.lineTo(x+q*.4f,y-q*.55f);a.close();c.drawPath(a,p);}if(id%7==0){p.setColor(0xFFB8E6FF);c.drawCircle(x,y+q*.35f,q*.22f,p);}}
  void encounter(boolean makeBoss){boss=makeBoss;enemy=makeBoss?Math.min(119,chapter*14+15):Math.min(119,zone*14+rng.nextInt(18));enemyHp=enemyMax();screen=2;invalidate();}
  void act(int a){if(a==0){hit(14+level*5+weapon[0]*8+rng.nextInt(14));}else if(a==1){int dmg=22+level*4;hit(dmg);Toast("Skill: "+skills[(enemy+level)%skills.length]);}else if(a==2){if(boss){Toast("Bosses cannot be tamed!");enemyTurn();}else{int chance=18+(enemyHp<enemyMax()/2?35:0)+(level>enemy/12?18:0);if(rng.nextInt(100)<chance){tame();return;}Toast("The monster resisted!");enemyTurn();}}else if(a==3){defend=true;enemyTurn();}else if(a==4){if(gold>=20){gold-=20;playerHp=Math.min(maxHp,playerHp+55);Toast("Potion restored HP!");}else Toast("Not enough gold!");}else{if(boss){Toast("The guardian blocks your escape!");enemyTurn();}else if(rng.nextInt(100)<60){screen=1;Toast("Escaped safely.");}else enemyTurn();}invalidate();}
  void hit(int dmg){enemyHp-=dmg;xp+=5;if(enemyHp<=0)victory();else enemyTurn();}
  void enemyTurn(){int dmg=5+rng.nextInt(11)+enemy%7; if(defend)dmg/=2;playerHp=Math.max(0,playerHp-dmg);defend=false;if(playerHp==0){gold=Math.max(0,gold-30);playerHp=maxHp;screen=1;Toast("You were carried back to town.");} }
  void victory(){wins++;gold+=20+enemy%25;xp+=30+enemy%15;for(int id:party)mlvl[id]++;if(xp>=level*60){xp-=level*60;level++;maxHp=80+level*40;playerHp=maxHp;Toast("Level up! You reached level "+level);}if(boss){chapter=Math.min(8,chapter+1);zone=Math.min(7,chapter-1);dungeon=Math.max(dungeon,chapter);dungeonFloor=0;Toast("Chapter cleared! New region unlocked!");}else if(rng.nextInt(100)<8&&party.size()>0){Toast("Your party feels stronger after the victory.");}playerHp=Math.min(maxHp,playerHp+20);screen=1;save();}
  void tame(){if(!caught[enemy]){caught[enemy]=true;tames++;mlvl[enemy]=level;if(party.size()<4)party.add(enemy);Toast(monsters[enemy]+" joined your side!");}victory();}
  void Toast(String q){Toast.makeText(getContext(),q,Toast.LENGTH_SHORT).show();if(vib!=null&&Build.VERSION.SDK_INT>=26)try{vib.vibrate(VibrationEffect.createOneShot(35,VibrationEffect.DEFAULT_AMPLITUDE));}catch(Exception e){}}
  void storyAdvance(){storySeen=true;if(chapter<8){chapter++;zone=Math.min(7,chapter-1);}save();screen=1;Toast("Chapter "+chapter+" unlocked!");}
  void buyGear(){if(gold>=50){gold-=50;weapon[0]=Math.min(4,weapon[0]+1);armor[0]=Math.min(4,armor[0]+1);maxHp+=10;playerHp=maxHp;save();Toast("Gear upgraded!");}else Toast("Need 50 gold.");}
  void breed(){if(party.size()<2){Toast("You need two party monsters.");return;}if(gold<75){Toast("Need 75 gold.");return;}gold-=75;int id=(party.get(0)+party.get(1)+rng.nextInt(120))%120;caught[id]=true;mlvl[id]=Math.max(1,(mlvl[party.get(0)]+mlvl[party.get(1)])/2);tames=Math.min(120,tames+1);if(party.size()<4)party.add(id);save();Toast("An egg hatched: "+monsters[id]+"!");}
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY(),w=getWidth(),h=getHeight(),d=D();
   if(screen==0){if(y>h*.55f){screen=1;invalidate();}return true;}
   if(screen==1){if(y>h*.69f&&y<h*.84f){if(x<w*.5f)encounter(false);else screen=8;return true;}if(y>h-80*d){int n=(int)(x/(w/4));screen=n+1;invalidate();return true;}if(y>h*.16f&&y<h*.50f){zone=Math.min(7,(int)((x/w)*4)+(y>h*.33f?4:0));invalidate();}return true;}
   if(screen==2){for(int i=0;i<6;i++){float xx=i%2==0?w*.08f:w*.54f,yy=425*d+(i/2)*52*d;if(x>=xx&&x<=xx+w*.38f&&y>=yy&&y<=yy+45*d){act(i);return true;}}return true;}
   if(screen==3){if(y>80*d&&y<h-70*d){int col=(int)(x/(w/3)),row=(int)((y-90*d)/(76*d));int id=(selected/15)*15+row*3+col;if(id<120)selected=id;invalidate();}else if(y>h-100*d&&x<w*.5f)selected=Math.max(0,selected-15);else selected=Math.min(119,selected+15);return true;}
   if(screen==4){if(y>115*d&&y<430*d){int i=(int)((y-120*d)/(62*d));if(i==0){playerHp=maxHp;Toast("Rested at the inn.");}else if(i==1)buyGear();else if(i==2){screen=8;}else if(i==3)screen=6;else if(i==4){gold+=100;Toast("Merchant paid you 100 gold for rare finds.");}save();invalidate();}return true;}
   if(screen==5){if(y>380*d){buyGear();invalidate();}return true;}
   if(screen==6){if(y>220*d&&y<330*d)breed();return true;}
   if(screen==7){if(y>420*d){dungeonFloor++;if(dungeonFloor>=8){dungeonFloor=0;encounter(true);}else encounter(false);}return true;}
   if(screen==8){if(y>340*d&&y<450*d)storyAdvance();return true;}
   return true;
  }
 }
}
