package com.example.checklistfirst;

import android.app.Activity;
import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.media.AudioManager;
import android.media.ToneGenerator;
import android.os.Bundle;
import android.os.SystemClock;
import android.os.VibrationEffect;
import android.os.Vibrator;
import android.view.MotionEvent;
import android.view.View;
import android.widget.Toast;
import java.util.Locale;
import java.util.Random;

public class MainActivity extends Activity {
    @Override public void onCreate(Bundle b) { super.onCreate(b); setTitle("Tap Galaxy"); setContentView(new TapView(this)); }

    static class TapView extends View {
        final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), t=new Paint(Paint.ANTI_ALIAS_FLAG); final Random rng=new Random();
        final SharedPreferences save; final ToneGenerator sound=new ToneGenerator(AudioManager.STREAM_MUSIC,70); final Vibrator vib;
        final RectF tapRect=new RectF(), bonusRect=new RectF(); final String[] up={"POWER GLOVE","AUTO TAPPER","CRIT CORE","COMBO ENGINE","COIN MAGNET","STAR REACTOR","DRONE SWARM","QUANTUM TAP","TIME DRIVE"};
        final String[] ud={"+1 tap","+2/sec","+5% crit","+0.5x combo","+10% income","+10/sec","+25/sec","+2 tap","faster combo + fever"};
        final int[] base={25,80,150,300,700,1800,5000,15000,30000};
        float den,tapScale=1f,fever,combo=1f; long coins,total,lifetime,lastFrame,comboUntil,goldUntil,eventUntil,bossUntil,lastDaily,play;
        int tapPower=1,auto,crit,comboLv,magnet,reactor,swarm,quantum,timeLv,prestige,taps,critTaps,bigCrit,highestCombo=10,upgrades,collectibles,achievements;
        int questDay,qt,qu,qe,dailyStreak,milestones,event=-1,bossHits,bossNeed; boolean frenzy,boss,pulse; int page;
        String eventText=""; long[] floatTime=new long[20]; String[] floatText=new String[20]; float[] floatX=new float[20],floatY=new float[20];

        TapView(Context c){ super(c); den=getResources().getDisplayMetrics().density; save=c.getSharedPreferences("tap_galaxy",Context.MODE_PRIVATE); vib=(Vibrator)c.getSystemService(Context.VIBRATOR_SERVICE);
            coins=save.getLong("coins",0); total=save.getLong("total",0); lifetime=save.getLong("lifetime",0); tapPower=save.getInt("tap",1); auto=save.getInt("auto",0); crit=save.getInt("crit",0); comboLv=save.getInt("combo",0); magnet=save.getInt("magnet",0); reactor=save.getInt("reactor",0); swarm=save.getInt("swarm",0); quantum=save.getInt("quantum",0); timeLv=save.getInt("time",0); prestige=save.getInt("prestige",0); taps=save.getInt("taps",0); critTaps=save.getInt("critTaps",0); bigCrit=save.getInt("bigCrit",0); highestCombo=save.getInt("highestCombo",10); upgrades=save.getInt("upgrades",0); collectibles=save.getInt("collectibles",0); achievements=save.getInt("achievements",0); questDay=save.getInt("questDay",0); qt=save.getInt("qt",0); qu=save.getInt("qu",0); qe=save.getInt("qe",0); dailyStreak=save.getInt("streak",0); lastDaily=save.getLong("daily",0); milestones=save.getInt("milestones",0); play=save.getLong("play",0);
            int today=(int)(System.currentTimeMillis()/86400000L); if(today!=questDay){questDay=today;qt=qu=qe=0;}
            long closed=Math.max(0,(System.currentTimeMillis()-save.getLong("closed",System.currentTimeMillis()))/1000); if(closed>60&&perSec()>0){long off=Math.min(999999999999L,(long)(closed*perSec()*mult()));add(off);Toast.makeText(c,"Offline earnings +"+fmt(off),Toast.LENGTH_LONG).show();}
            t.setTypeface(android.graphics.Typeface.create("sans",android.graphics.Typeface.BOLD)); setLayerType(View.LAYER_TYPE_SOFTWARE,null); checkAch();
        }
        float d(float x){return x*den;} float W(){return getWidth();} float H(){return getHeight();}
        int lvl(int i){switch(i){case 0:return tapPower-1;case 1:return auto;case 2:return crit;case 3:return comboLv;case 4:return magnet;case 5:return reactor;case 6:return swarm;case 7:return quantum;default:return timeLv;}}
        long cost(int i){return (long)Math.min(9.22e18,base[i]*Math.pow(1.62,lvl(i)));} long perSec(){return auto*2L+reactor*10L+swarm*25L;}
        float mult(){return (1+magnet*.10f)*(1+prestige*.25f)*(frenzy?10:1)*(event==0?2:1);} float comboCap(){return 1+comboLv*.5f;}
        void tone(int x){if(sound!=null)sound.startTone(x,45);} void buzz(){if(vib!=null&&vib.hasVibrator())vib.vibrate(VibrationEffect.createOneShot(15,VibrationEffect.DEFAULT_AMPLITUDE));}
        void add(long n){if(n<=0)return;coins+=n;total+=n;lifetime+=n;qe+=(int)Math.min(Integer.MAX_VALUE,n);checkMilestones();checkAch();}
        void floating(String s,float x,float y){long n=SystemClock.elapsedRealtime();for(int i=0;i<floatText.length;i++)if(n-floatTime[i]>700){floatText[i]=s;floatX[i]=x;floatY[i]=y;floatTime[i]=n;return;}}

        @Override protected void onDraw(Canvas c){long now=SystemClock.elapsedRealtime();float dt=lastFrame==0?0:Math.min(.1f,(now-lastFrame)/1000f);lastFrame=now;play+=(long)dt;
            long income=(long)(perSec()*dt*mult());if(income>0)add(income); if(pulse){tapScale+=(1-tapScale)*.25f;if(Math.abs(tapScale-1)<.01f){tapScale=1;pulse=false;}}
            if(frenzy&&now>eventUntil)frenzy=false; if(event>=0&&now>eventUntil)event=-1; if(boss&&now>bossUntil){boss=false;Toast.makeText(getContext(),"Boss escaped!",Toast.LENGTH_SHORT).show();}
            if(event<0&&now%10000<40&&rng.nextInt(4)==0){event=rng.nextInt(3);eventUntil=now+30000;eventText=event==0?"2X POINTS":event==1?"CRITICAL FRENZY":"MEGA TAP";Toast.makeText(getContext(),"EVENT: "+eventText,Toast.LENGTH_SHORT).show();tone(ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD);}
            if(!boss&&now%45000<40&&rng.nextInt(3)==0){boss=true;bossHits=0;bossNeed=25+prestige*10;bossUntil=now+20000;Toast.makeText(getContext(),"BOSS INCOMING — 20 SECONDS!",Toast.LENGTH_SHORT).show();}
            if(page==0)game(c); else if(page==1)stats(c); else collection(c); save(); postInvalidateDelayed(Math.max(16,33-timeLv*2));
        }
        void background(Canvas c){c.drawColor(frenzy?Color.rgb(45,10,65):Color.rgb(8,10,28));p.setColor(frenzy?Color.rgb(110,25,115):Color.rgb(22,27,65));c.drawCircle(W()*.15f,H()*.2f,d(95),p);p.setColor(Color.rgb(17,22,52));c.drawCircle(W()*.87f,H()*.28f,d(120),p);p.setColor(Color.WHITE);for(int i=0;i<45;i++)c.drawCircle((i*97)%Math.max(1,getWidth()),(i*173+30)%Math.max(1,(int)(H()*.75f)),d(i%5==0?1.5f:.7f),p);}
        void header(Canvas c){p.setColor(Color.rgb(17,22,52));c.drawRoundRect(d(10),d(8),W()-d(10),d(78),d(18),d(18),p);t.setTextAlign(Paint.Align.LEFT);t.setColor(Color.rgb(155,180,225));t.setTextSize(d(10));c.drawText("TAP GALAXY",d(22),d(26),t);t.setColor(Color.WHITE);t.setTextSize(d(23));c.drawText(fmt(coins),d(22),d(57),t);t.setTextAlign(Paint.Align.RIGHT);t.setTextSize(d(9));t.setColor(Color.rgb(120,230,190));c.drawText("+"+fmt(perSec())+" / SEC",W()-d(20),d(26),t);c.drawText("REBIRTHS "+prestige,W()-d(20),d(42),t);}
        void nav(Canvas c){float y=H()-d(46);p.setColor(Color.rgb(17,22,52));c.drawRect(0,y,W(),H(),p);t.setTextAlign(Paint.Align.CENTER);t.setTextSize(d(10));String[] n={"GAME","STATS","COLLECT"};for(int i=0;i<3;i++){t.setColor(page==i?Color.WHITE:Color.rgb(120,135,175));c.drawText(n[i],W()*(i+.5f)/3,y+d(28),t);}}
        void game(Canvas c){background(c);header(c);long now=SystemClock.elapsedRealtime();
            p.setColor(Color.rgb(30,35,70));c.drawRoundRect(d(25),d(88),W()-d(25),d(103),d(8),d(8),p);p.setColor(frenzy?Color.rgb(255,100,220):Color.rgb(245,175,65));c.drawRoundRect(d(25),d(88),d(25)+(W()-d(50))*fever,d(103),d(8),d(8),p);t.setTextAlign(Paint.Align.CENTER);t.setTextSize(d(9));t.setColor(Color.WHITE);c.drawText(frenzy?"TAP FRENZY ×10!":"FEVER METER",W()/2,d(100),t);
            float cy=H()*.255f,r=Math.min(W()*.29f,d(90))*tapScale;tapRect.set(W()/2-r,cy-r,W()/2+r,cy+r);p.setShadowLayer(d(28),0,d(5),Color.rgb(70,120,255));p.setColor(frenzy?Color.rgb(255,85,210):Color.rgb(65,105,240));c.drawCircle(W()/2,cy,r+d(12),p);p.clearShadowLayer();p.setColor(frenzy?Color.rgb(255,205,245):Color.rgb(105,220,255));c.drawCircle(W()/2,cy,r,p);p.setColor(Color.rgb(30,55,170));c.drawCircle(W()/2,cy,r*.77f,p);t.setTextAlign(Paint.Align.CENTER);t.setColor(Color.WHITE);t.setTextSize(d(19));c.drawText("TAP!",W()/2,cy+d(7),t);t.setTextSize(d(10));t.setColor(Color.rgb(190,225,255));c.drawText("POWER CORE",W()/2,cy+d(25),t);t.setTextSize(d(11));t.setColor(Color.rgb(240,200,80));c.drawText("COMBO ×"+String.format(Locale.US,"%.1f",combo),W()/2,cy+r+d(25),t);
            if(goldUntil<now&&rng.nextInt(1000)<2)goldUntil=now+7000;if(goldUntil>now){float gx=W()*.78f,gy=H()*.18f;bonusRect.set(gx-d(28),gy-d(28),gx+d(28),gy+d(28));p.setShadowLayer(d(20),0,0,Color.YELLOW);p.setColor(Color.rgb(255,205,55));c.drawCircle(gx,gy,d(24),p);p.clearShadowLayer();t.setTextSize(d(8));t.setColor(Color.WHITE);c.drawText("BONUS",gx,gy+d(3),t);}
            if(boss){float by=H()*.35f;p.setColor(Color.rgb(105,25,50));c.drawRoundRect(d(20),by,W()-d(20),by+d(38),d(12),d(12),p);t.setTextSize(d(11));t.setColor(Color.WHITE);c.drawText("BOSS  "+bossHits+" / "+bossNeed,W()/2,by+d(16),t);t.setTextSize(d(8));c.drawText("TAP TO DEFEAT",W()/2,by+d(30),t);}
            if(event>=0){t.setTextSize(d(10));t.setColor(Color.rgb(255,205,85));c.drawText(eventText+"  "+Math.max(0,(eventUntil-now)/1000)+"s",W()/2,H()*.40f,t);}
            float sy=event>=0?H()*.42f:H()*.40f;p.setColor(Color.rgb(17,23,54));c.drawRoundRect(d(12),sy,W()-d(12),sy+d(52),d(14),d(14),p);t.setTextSize(d(9));t.setColor(Color.rgb(145,160,205));String[] s={"TAPS","CRIT","COMBO","MEDALS"};float[] x={.15f,.38f,.64f,.86f};for(int i=0;i<4;i++)c.drawText(s[i],W()*x[i],sy+d(18),t);t.setTextSize(d(13));t.setColor(Color.WHITE);c.drawText(fmt(taps),W()*.15f,sy+d(40),t);c.drawText(fmt(critTaps),W()*.38f,sy+d(40),t);c.drawText("x"+String.format(Locale.US,"%.1f",highestCombo/10f),W()*.64f,sy+d(40),t);c.drawText(achievements+"/12",W()*.86f,sy+d(40),t);
            upgrades(c,sy+d(62));floats(c);nav(c);
        }
        void upgrades(Canvas c,float top){t.setTextAlign(Paint.Align.LEFT);t.setTextSize(d(14));t.setColor(Color.WHITE);c.drawText("UPGRADE SHOP",d(18),top,t);float y=top+d(7),gap=d(3),h=Math.max(d(24),Math.min(d(33),(H()-y-d(53)-gap*8)/9f));for(int i=0;i<9;i++){float yy=y+i*(h+gap);p.setColor(Color.rgb(20,27,61));c.drawRoundRect(d(9),yy,W()-d(9),yy+h,d(8),d(8),p);t.setTextAlign(Paint.Align.LEFT);t.setTextSize(d(7));t.setColor(Color.WHITE);c.drawText(up[i]+" LV"+lvl(i),d(18),yy+d(12),t);t.setColor(Color.rgb(150,170,210));c.drawText(ud[i],d(18),yy+d(23),t);long price=cost(i);p.setColor(coins>=price?Color.rgb(42,165,112):Color.rgb(53,60,86));c.drawRoundRect(W()-d(80),yy+d(3),W()-d(11),yy+h-d(3),d(6),d(6),p);t.setTextAlign(Paint.Align.CENTER);t.setTextSize(d(7));t.setColor(Color.WHITE);c.drawText(fmt(price),W()-d(45),yy+d(13),t);c.drawText("BUY",W()-d(45),yy+d(24),t);}}
        void floats(Canvas c){long n=SystemClock.elapsedRealtime();t.setTextAlign(Paint.Align.CENTER);t.setTextSize(d(12));for(int i=0;i<floatText.length;i++)if(n-floatTime[i]<700){t.setColor(Color.WHITE);c.drawText(floatText[i],floatX[i],floatY[i]-(n-floatTime[i])*.06f,t);}}
        void stats(Canvas c){background(c);header(c);t.setTextAlign(Paint.Align.LEFT);t.setTextSize(d(20));t.setColor(Color.WHITE);c.drawText("STATISTICS",d(20),d(112),t);String[][] r={{"Total taps",fmt(taps)},{"Lifetime points",fmt(lifetime)},{"Biggest critical","×"+bigCrit},{"Critical taps",fmt(critTaps)},{"Highest combo","×"+String.format(Locale.US,"%.1f",highestCombo/10f)},{"Play time",(play/3600)+"h "+((play%3600)/60)+"m"},{"Rebirths",""+prestige},{"Upgrades bought",fmt(upgrades)},{"Tap power",fmt(tapPower)},{"Auto income",fmt(perSec())},{"Daily streak",""+dailyStreak}};float y=d(145);for(String[] a:r){p.setColor(Color.rgb(18,24,56));c.drawRoundRect(d(15),y,W()-d(15),y+d(39),d(9),d(9),p);t.setTextAlign(Paint.Align.LEFT);t.setTextSize(d(10));t.setColor(Color.rgb(155,175,215));c.drawText(a[0],d(28),y+d(25),t);t.setTextAlign(Paint.Align.RIGHT);t.setTextSize(d(12));t.setColor(Color.WHITE);c.drawText(a[1],W()-d(28),y+d(25),t);y+=d(44);}nav(c);}
        void collection(Canvas c){background(c);header(c);t.setTextAlign(Paint.Align.LEFT);t.setColor(Color.WHITE);t.setTextSize(d(19));c.drawText("QUESTS + COLLECTION",d(18),d(108),t);p.setColor(Color.rgb(20,27,61));c.drawRoundRect(d(15),d(122),W()-d(15),d(205),d(14),d(14),p);t.setTextSize(d(11));t.setColor(Color.rgb(245,200,85));c.drawText("DAILY QUESTS",d(28),d(145),t);t.setTextSize(d(9));t.setColor(Color.WHITE);c.drawText("Tap 250: "+Math.min(qt,250)+" / 250",d(30),d(165),t);c.drawText("Buy 5 upgrades: "+Math.min(qu,5)+" / 5",d(30),d(181),t);c.drawText("Earn 10K: "+Math.min(qe,10000)+" / 10,000",d(30),d(197),t);t.setColor(Color.rgb(130,235,185));c.drawText("Relics "+collectibles+"/20",W()-d(90),d(165),t);
            t.setTextSize(d(14));t.setColor(Color.WHITE);c.drawText("MILESTONES",d(18),d(230),t);long[] mv={100,1000,10000,1000000,1000000000L};String[] mn={"100","1K","10K","1M","1B"};for(int i=0;i<5;i++){float xx=d(18)+i*(W()-d(36))/5f;p.setColor((milestones&(1<<i))!=0?Color.rgb(45,170,115):Color.rgb(35,42,75));c.drawCircle(xx+d(22),d(265),d(22),p);t.setTextAlign(Paint.Align.CENTER);t.setTextSize(d(8));t.setColor(Color.WHITE);c.drawText(mn[i],xx+d(22),d(268),t);}
            t.setTextAlign(Paint.Align.LEFT);t.setTextSize(d(14));c.drawText("ACHIEVEMENTS",d(18),d(320),t);String[] a={"Tap 100","Tap 1K","Tap 10K","Earn 100K","Glove LV10","First Rebirth","10 Criticals","100 Criticals","Combo x5","Earn 1M","Earn 1B","Collect Relic"};for(int i=0;i<12;i++){float xx=d(15)+(i%2)*(W()/2-d(5)),yy=d(335)+(i/2)*d(30);p.setColor(i<achievements?Color.rgb(45,170,115):Color.rgb(25,31,60));c.drawRoundRect(xx,yy,xx+W()/2-d(10),yy+d(25),d(7),d(7),p);t.setTextAlign(Paint.Align.LEFT);t.setTextSize(d(8));t.setColor(Color.WHITE);c.drawText((i<achievements?"✓ ":"○ ")+a[i],xx+d(8),yy+d(16),t);}nav(c);}

        void tap(){long now=SystemClock.elapsedRealtime();if(boss){bossHits++;buzz();floating("BOSS HIT!",W()/2,H()*.35f);if(bossHits>=bossNeed){boss=false;long reward=10000L*(prestige+1);add(reward);collectibles=Math.min(20,collectibles+1);Toast.makeText(getContext(),"BOSS DEFEATED +"+fmt(reward),Toast.LENGTH_LONG).show();tone(ToneGenerator.TONE_PROP_ACK);}return;}
            long gain=tapPower+quantum*2L;int critMult=0;float chance=Math.min(.95f,crit*.05f*(event==1?4:1));if(rng.nextFloat()<chance){float r=rng.nextFloat();critMult=r<.01f?100:(r<.08f?10:5);gain*=critMult;critTaps++;bigCrit=Math.max(bigCrit,critMult);}
            if(now<comboUntil)combo=Math.min(comboCap(),combo+.1f);else combo=1;comboUntil=now+Math.max(600,1300-timeLv*45);highestCombo=Math.max(highestCombo,Math.round(combo*10));fever=Math.min(1,fever+.012f+timeLv*.003f+(critMult>0?.025f:0));if(fever>=1&&!frenzy){frenzy=true;eventUntil=now+10000;fever=0;Toast.makeText(getContext(),"🔥 TAP FRENZY ×10 — 10 SECONDS!",Toast.LENGTH_SHORT).show();tone(ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD);}
            if(event==2)gain*=10;long reward=Math.max(1,Math.round(gain*combo*mult()));add(reward);taps++;qt++;pulse=true;tapScale=.86f;buzz();floating((critMult>0?"CRIT ×"+critMult+"  ":"")+"+"+fmt(reward),W()/2,H()*.255f);if(critMult>0)tone(ToneGenerator.TONE_PROP_BEEP);checkAch();}
        void buy(int i){long price=cost(i);if(coins<price)return;coins-=price;switch(i){case 0:tapPower++;break;case 1:auto++;break;case 2:crit++;break;case 3:comboLv++;break;case 4:magnet++;break;case 5:reactor++;break;case 6:swarm++;break;case 7:quantum++;break;default:timeLv++;}upgrades++;qu++;pulse=true;tone(ToneGenerator.TONE_PROP_ACK);checkAch();}
        void rebirth(){long need=100000L*(prestige+1);if(lifetime<need){Toast.makeText(getContext(),"Need "+fmt(need)+" lifetime points",Toast.LENGTH_SHORT).show();return;}prestige++;coins=0;tapPower=1;auto=crit=comboLv=magnet=reactor=swarm=quantum=timeLv=0;combo=1;tone(ToneGenerator.TONE_PROP_ACK);Toast.makeText(getContext(),"REBIRTH! Permanent +25% earnings",Toast.LENGTH_SHORT).show();}
        void daily(){long day=System.currentTimeMillis()/86400000L,last=lastDaily/86400000L;if(day==last)return;if(last>0&&day==last+1)dailyStreak++;else dailyStreak=1;long reward=250L*dailyStreak*(prestige+1);add(reward);lastDaily=System.currentTimeMillis();Toast.makeText(getContext(),"Daily reward +"+fmt(reward),Toast.LENGTH_SHORT).show();}
        void checkMilestones(){long[] v={100,1000,10000,1000000,1000000000L};for(int i=0;i<v.length;i++)if(lifetime>=v[i]&&(milestones&(1<<i))==0){milestones|=1<<i;long reward=v[i]/10;add(reward);collectibles=Math.min(20,collectibles+1);Toast.makeText(getContext(),"Milestone "+fmt(v[i])+"! +"+fmt(reward),Toast.LENGTH_SHORT).show();}}
        void checkAch(){int a=0;if(taps>=100)a++;if(taps>=1000)a++;if(taps>=10000)a++;if(lifetime>=100000)a++;if(tapPower>=10)a++;if(prestige>=1)a++;if(critTaps>=10)a++;if(critTaps>=100)a++;if(highestCombo>=50)a++;if(lifetime>=1000000)a++;if(lifetime>=1000000000L)a++;if(collectibles>0)a++;if(a>achievements){achievements=a;tone(ToneGenerator.TONE_PROP_BEEP);}}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_DOWN)return true;float x=e.getX(),y=e.getY();long now=SystemClock.elapsedRealtime();if(y>H()-d(50)){page=Math.min(2,(int)(x/(W()/3)));return true;}if(page!=0)return true;if(y<d(78)&&x>W()-d(150)){rebirth();return true;}if(tapRect.contains(x,y)){tap();performClick();return true;}if(goldUntil>now&&bonusRect.contains(x,y)){goldUntil=0;long reward=5000L*(prestige+1);add(reward);collectibles=Math.min(20,collectibles+1);floating("GOLDEN +"+fmt(reward),x,y);tone(ToneGenerator.TONE_CDMA_HIGH_L);buzz();return true;}float sy=event>=0?H()*.42f:H()*.40f,top=sy+d(62),gap=d(3),h=Math.max(d(24),Math.min(d(33),(H()-top-d(53)-gap*8)/9f));for(int i=0;i<9;i++){float yy=top+d(7)+i*(h+gap);if(y>=yy&&y<=yy+h&&x>W()-d(95)){buy(i);return true;}}if(now-lastDaily>86400000L)daily();return true;}
        @Override public boolean performClick(){super.performClick();return true;}
        void save(){save.edit().putLong("coins",coins).putLong("total",total).putLong("lifetime",lifetime).putInt("tap",tapPower).putInt("auto",auto).putInt("crit",crit).putInt("combo",comboLv).putInt("magnet",magnet).putInt("reactor",reactor).putInt("swarm",swarm).putInt("quantum",quantum).putInt("time",timeLv).putInt("prestige",prestige).putInt("taps",taps).putInt("critTaps",critTaps).putInt("bigCrit",bigCrit).putInt("highestCombo",highestCombo).putInt("upgrades",upgrades).putInt("collectibles",collectibles).putInt("achievements",achievements).putInt("questDay",questDay).putInt("qt",qt).putInt("qu",qu).putInt("qe",qe).putInt("streak",dailyStreak).putLong("daily",lastDaily).putInt("milestones",milestones).putLong("play",play).putLong("closed",System.currentTimeMillis()).apply();}
        String fmt(long n){if(n<1000)return ""+n;String[] u={"K","M","B","T","Qa","Qi"};double v=n;int i=-1;while(v>=1000&&i<u.length-1){v/=1000;i++;}if(i==u.length-1&&v>=1000)return String.format(Locale.US,"%.2e",(double)n);return String.format(Locale.US,"%.1f%s",v,u[i]);}
    }
}
